version: '2.1'
services:

  mysql:
    image: mysql:8.0.15
    container_name: mySQLEcosystem
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'Ad456Adf'
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - /storage/docker/mysql-datadir:/var/lib/mysql

  firstms:
    build: firstms
    ports: 
      - 9090:9090
    links:
      - mysql
    depends_on:
      - mysql
  jpa:
    build: jpa
    ports: 
      - 9091:9091
    links:
      - mysql
    depends_on:
      - mysql
  security:
    build: security
    ports: 
      - 8084:8084
    links:
      - mysql
    depends_on:
      - mysql
  rates:
    build: rates
    ports: 
      - 8081:8081
    links:
      - mysql
    depends_on:
      - mysql
  store-api:
    build: store-api
    ports: 
      - 8083:8083
    links:
      - mysql
    depends_on:
      - mysql